services:
  stats-server:
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://stats-db:5432/stats-db
    build:
      context: .
      dockerfile: ./stats/statsServer/Dockerfile
    ports:
      - "9090:9091"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9090/actuator/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s
    container_name: stats-server
    depends_on:
      - stats-db
    networks:
      - stats-network

  stats-db:
    image: postgres:16.1
    container_name: stats-db
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: password
      POSTGRES_DB: stats-db
#    ports:
#      - "6432:5432"
    restart: unless-stopped
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U root -d stats-db" ]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - stats-network

  adminer:
    image: adminer
    container_name: adminer
    ports:
      - "8081:8080"
    environment:
      ADMINER_DEFAULT_SERVER: stats-db
    depends_on:
      - stats-db
      - ewm-db
    restart: unless-stopped
    networks:
      - stats-network
      - ewm-network

  ewm-service:
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://ewm-db:5432/ewm-db
    build:
      context: .
      dockerfile: ./main/Dockerfile
    ports:
      - "8080:8080"
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8080/actuator/health" ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
    container_name: ewm-service
    depends_on:
      - ewm-db
    networks:
      - ewm-network

  ewm-db:
    image: postgres:16.1
    container_name: ewm-db
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: password
      POSTGRES_DB: ewm-db
#    ports:
#      - "5432:5432"
    restart: unless-stopped
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U root -d ewm-db" ]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - ewm-network

networks:
  stats-network:
    driver: bridge
  ewm-network:
    driver: bridge
